# Generated by Django 5.1 on 2024-08-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
